version: '3.4'

services:
  adncgatewayocelot:
    image: adncgatewayocelot:latest
    container_name: "adncgatewayocelot-dev"
    #restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    #  - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=SkyAPM.Agent.AspNetCore
    ports:
      - "8888:8080"
    extra_hosts:
      - "localhost:172.80.0.4" # 映射 onsul_client ip
    networks:
      - docker-compose_adnc_consul_webapi

networks:
  docker-compose_adnc_consul_webapi:
    external: true
